services:
  noc-noc-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: noc-noc-app
    ports:
      - "${APP_PORT:-8092}:3000"
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    networks:
      - proxy
      - database

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9091:9090"
    networks:
      - proxy

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - proxy

  fortigate-exporter:
    image: sistemasstratio/fortigate-exporter:latest
    container_name: fortigate-exporter
    restart: unless-stopped
    ports:
      - "9710:9710"
    volumes:
      - ./fortigate/fortigate.yaml:/etc/fortigate_exporter.yaml:ro
    command:
      - '-config'
      - '/etc/fortigate_exporter.yaml'
    networks:
      - proxy

  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: unless-stopped
    environment:
      - UPTIME_KUMA_DB_TYPE=mariadb
      - UPTIME_KUMA_DB_HOSTNAME=mariadb
      - UPTIME_KUMA_DB_PORT=3306
      - UPTIME_KUMA_DB_NAME=kuma
      - UPTIME_KUMA_DB_USERNAME=administrador
      - UPTIME_KUMA_DB_PASSWORD=S1stemas3031*.
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - "3001:3001"
    networks:
      - proxy
      - database

networks:
  database:
    name: database
    external: true
  proxy:
    name: proxy
    external: true
