global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'noc-noc-webhook'

receivers:
  - name: 'noc-noc-webhook'
    webhook_configs:
      - url: 'http://noc-noc-app:3000/api/webhooks/prometheus?token=37a0e14caec38aa2b5d72755b1a32c35059257d1139ecbe726129bfcfb3af2e1'
        send_resolved: true
