global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'noc-noc-webhook'

receivers:
  - name: 'noc-noc-webhook'
    webhook_configs:
      - url: 'http://noc-noc-app:3000/api/webhooks/prometheus'
        send_resolved: true
